### PR TITLE
Add method to limit reply-chain length

### PR DESCRIPTION
**Pull request by ningyuansg**
Following the banning of /u/RedditNewsPostBot, it may be required to compromise with the mods of /r/Singapore to allow the bot to post once again, but with limits to the lengths of the comment chain.

It would be preferable to be able to get the bot unbanned without modifications to its current behaviour.

But just in case, this is a quick fix. **This is not tested, nor integrated with the bot at all, though**. Since I didn't really take the time to read and understand the original code enough to do that. It is just a single method, by itself.

All the best, and I would understand if you would want to close this PR and make the changes yourself instead. ✌️ 
***
(Commit Message below)
```
Add reply_article_restricted

reply_article_restricted is a modified form of reply_article.
It has the added function of being able to limit the length of its
reply chain according to the additional argument comment_limit (int).

Should the reply chain exceed the comment_limit, the article will
be cutoff at the last allowed comment in the reply chain.

Additionally, the last allowed comment in the reply chain will be
appended with the message,

"Comment limit reached. Read more from the original post.\n"

NOTE: THIS CODE HAS NOT BEEN TESTED. PLEASE TEST IT BEFORE MERGE.
THIS FUNCTION HAS NOT BEEN IMPLEMENTED. IT IS CURRENTLY NOT CALLED
IN ANY PART OF CODE IN THIS REPOSITORY.
```

### CODE REVIEW

**Comment by LFlare** [comment]
Would you care to modify the existing `reply_article()` method by adding a default value assignment to `comment_limit`?

**Comment by ningyuansg** [comment]
@LFlare It's been done. Once again though, I should remind you I haven't tested any of this.

**Comment by LFlare** [comment]
Alright, thanks for the work done @ningyuansg. I'll revisit this pull request if this bot has any chance of being unbanned.

**Comment by LFlare** [comment]
Sorry about this, it's been banned for good, so I'll close this PR.

**Pull request closed without merging**
