### PR TITLE
Fix comment template url

### PR DESCRIPTION
**Pull request by emansih**
Minor url bug fix to your Reddit profile

### CODE REVIEW

**Comment by LFlare** [comment]
Thanks for your pull request but this 'typo' is actually intended, as it allows me to link to my user profile without receiving a notification from it c: Thanks for your help though.

**Comment by emansih** [comment]
oh ok, but it does not link to your profile when the link is a 404?

**Comment by emansih** [comment]
besides, you can block user from messaging you via https://www.reddit.com/prefs/blocked/

**Comment by LFlare** [comment]
Thank you for pointing this out to me, it seems that the link stopped working awhile ago, I'll push a commit soon.

**Pull request closed without merging**
